/**/
/**/
/*AUTHOR: YUE PAN*/
/*DATE: 09/28/2020*/
/*GOAL: 1. CREATE 1 DELIVERY FOR 3.2. 3.3.30 3.3.100 3.3.275 MEASURES FOR HCS NY UPDATE*/
/*	  2. CREATE 4 DELIVEREIS FOR HCS*/
/**/
/*THERE ARE 5 DELIVERY FILES TO HCS DELIVERIES*/
/**/
/*DEA32_FINAL_&DATE.*/
/*DEA32_HCS_NYONLY_&DATE.*/
/*DEA32_HCS_NYONLY_nocom_&DATE.*/
/*DEA32_HCS_ALLSTATE_&DATE.*/
/*DEA32_HCS_ALLSTATE_nocom_&DATE.*/
/**/
/**/
/*	  3.CREATE 1 INTERNAL DELIVERY AND USE IT AS THE PARENT TABLE FOR SUMMARY.EXCEL*/
/**/
/*	  DEA32_FINAL_EXCEL_&DATE.*/
/**/
/**/
/*STEPS:*/
/**/
/*0. IMPORT DEA DATA:*/
/*   A. NEEDS TO DOWNLOAD UPDATED DATA AND CHANGE THE CORRECT DIRECTION */
/*   B. CHECK PROC FORMAT;*/
/*			VALUE $record_vintagel*/
/**/
/*			IF INCLUDED THE MOST UPDATED MONTH*/
/*0.1 SET UP DATE AND UPDATE VERSION*/
/*3.0 CAL_1*/
/*	CHECK YEAR IF YEAR REACHED 12 FOR THE CURRENT YEAR */
/*4.1 CHECK POPULATION (FULL COUNTY FROM CDC WONDER, PARTIAL FROM ACS)*/
/*4.4 CHECK QUARTER IF QUARTER REACHED THE CURRENT QUARTER, IF NOT DELETE*/
/*    DEA32_FINAL_EXCEL_&DATE.*/
/*	DEA32_FINAL_&DATE.*/
/*4.4.1 CREATE INTERNAL COMPARISON*/
/*5.0 EXPORT TO TWO RAW FOLDERS, NEEDS TO CREATE A NEW FOLDER */
/*    AND PASTE THEM FROM THE RAW FOLDER TO THE CORRECT NEW FOLDER*/
/**/
/**/
/**/
/**/
/**/

proc options option=work;
run;